### ISSUE TITLE
Update for php7.0

### ISSUE THREAD

**Issue by tomhoag** [andrewpuch/phpmyadmin_connect_to_rds#2]
`apt-get install apache2 php7.0 php7.0-cli php7.0-fpm php7.0-gd php-ssh2 libapache2-mod-php7.0 php7.0-mcrypt mysql-server php7.0-mysql git unzip zip postfix php7.0-curl mailutils php7.0-json phpmyadmin -y`

**Comment by andrewpuch** [comment]
Thanks @tomhoag I'll put this in.
